framework:
    secret: '%env(string:APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    trusted_proxies: '%env(string:TRUSTED_PROXIES)%'
    #trusted_headers: '%env(json:TRUSTED_HEADERS)%'