security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: app_provider
                enable_csrf: true
                login_path: app_security_login
                check_path: app_security_login
                default_target_path: app_homepage
                always_use_default_target_path: false
                use_referer: true
            remember_me:
                secret: '%env(string:APP_SECRET)%'
                lifetime: 31536000 # 1 year
                secure: auto
            logout:
                path: app_security_logout
            custom_authenticators:
                - App\Security\UsernameOrEmailPasswordAuthenticator
            lazy: true

    access_control:
        - { path: ^/_wdt, roles: PUBLIC_ACCESS }
        - { path: ^/_profiler/, role: PUBLIC_ACCESS }
        - { path: ^/user, role: PUBLIC_ACCESS }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/first-connection, role: PUBLIC_ACCESS }
        - { path: ^/translations, role: PUBLIC_ACCESS }
        - { path: ^/$, role: PUBLIC_ACCESS }
        - { path: ^/admin/_trans, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }

