security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt|error)
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_provider
            json_login:
                check_path: /api/authentication_token
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
        main:
            pattern: ^/
            form_login:
                provider: app_provider
                enable_csrf: true
                login_path: app_security_login
                check_path: app_security_login
                default_target_path: app_homepage
                always_use_default_target_path: false
                use_referer: true
            remember_me:
                secret: '%env(string:APP_SECRET)%'
                lifetime: 31536000 # 1 year
                secure: auto
            logout:
                path: app_security_logout
            custom_authenticators:
                - App\Security\UsernameOrEmailPasswordAuthenticator

    access_control:
        - { path: ^/user, role: PUBLIC_ACCESS }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/first-connection, role: PUBLIC_ACCESS }
        - { path: ^/translations, role: PUBLIC_ACCESS }
        - { path: ^/api$, role: PUBLIC_ACCESS }
        - { path: ^/api/authentication_token, roles: PUBLIC_ACCESS }
        - { path: ^/$, role: PUBLIC_ACCESS }
        - { path: ^/, role: ROLE_USER }

