version: '3'

services:
    php:
        build: ./docker/php
        ports:
            - 9000:9000
        links:
            - postgres
        volumes:
            - .:/var/www/koillection
            - ./logs/symfony:/var/www/symfony/app/logs

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - .:/var/www/koillection
            - ./logs/symfony:/var/www/symfony/app/logs

    postgres:
        container_name: postgres
        image: postgres:alpine
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5432:5432
        volumes:
            - "./docker/volumes/postgresql:/var/lib/postgresql/data"
