#This docker-compose file is provided for dev purposes
version: '3'

services:
    #FPM image
    koillection:
        container_name: koillection
        image: docker.pkg.github.com/benjaminjonard/koillection/fpm:dev
        restart: always
        ports:
            - 80:80
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=m6iFpZTkR1U6klSvLtRF
            - DB_VERSION=12.2
            - PHP_TZ=Europe/Paris
        depends_on:
            - postgres
            - mysql
        volumes:
            - "./docker/volumes/koillection/public/uploads:/var/www/koillection/public/uploads"
            - ./:/var/www/koillection

    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=m6iFpZTkR1U6klSvLtRF
        ports:
            - 5432:5432
        volumes:
            - "./docker/volumes/postgresql:/var/lib/postgresql/data"

    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=m6iFpZTkR1U6klSvLtRF
            - MYSQL_DATABASE=koillection
            - MYSQL_USER=root
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"
