controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

app_homepage:
  path: /collections
  defaults: { _controller: 'App\Controller\CollectionController::index' }
  methods:  [GET]

app_security_logout:
  path: /logout