name: Publish beta Docker image
on:
  push:
    branches:
      - master
jobs:
  publish_beta_to_registries:
    name: Publish beta image for Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: master
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: koillection/koillection
          tags: |
            beta
          build_args: |
            GITHUB_RELEASE=master
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: koillection/koillection/fpm
          tags: |
            beta
          build_args: |
            GITHUB_RELEASE=master