name: Build release image for Docker Hub
on:
  release:
    types: [published]
jobs:
  push_to_docker_hub:
    name: Build release image for Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: php8.0
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: koillection/koillection
          tags: latest,1.2.3
          build_args: GITHUB_RELEASE=master
