name: Build release image for GitHub Packages
on:
  release:
    types: [published]
jobs:
  push_to_git_hub_packages:
    name: Build release image for GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: master
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: koillection/koillection/fpm
          tags: |
            latest
          build_args: |
            GITHUB_RELEASE=${{ github.event.release.tag_name }}
