name: Build beta image for GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  push_to_git_hub_packages:
    name: Build beta image for GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: php8.0
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: koillection/koillection/fpm
          tags: |
            beta
          build_args: |
            GITHUB_RELEASE=master