name: Build release image for GitHub Packages
on:
  release:
    types: [published]
jobs:
  push_to_git_hub_packages:
    name: Build release image for GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: php8.0
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: koillection/koillection/fpm
          tags: latest,1.2.3
          build_args: GITHUB_RELEASE=master
