name: Build and push release Docker images
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push to GitHub Packages and Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: master
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: koillection/koillection
          tags: |
            latest
            ${{ github.event.release.tag_name }}
          build_args: |
            GITHUB_RELEASE=${{ github.event.release.tag_name }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: koillection/koillection/fpm
          tags: |
            latest
            ${{ github.event.release.tag_name }}
          build_args: |
            GITHUB_RELEASE=${{ github.event.release.tag_name }}
